## These functions are part of JH R Programming course second assignment.
## makeChacheMatrix will cache a matrix and its inverse, while cacheSolve
## will either use the stored inverse value or solve X and store the 
## result in the cache.


## Creates data caches.
makeCacheMatrix <- function(x = matrix()) {

  I <- NULL # Initialize I, future inverse matrix 
  
  # Define set function.
  set <- function(y) { 
    x <<- y # Sets the value of X in the previous environment
    I <<- NULL # Same for I.
  }
  
  # Define get function
  get <- function() x # Only reads x value
  
  # Define setInverse function
  ## Sets the value of I in the previous enviroment, will be used with "solve()"
  ## within the function cacheSolve().
  setInverse <- function(Inverse) I <<- Inverse 
  
  # Define getInverse
  getInverse <- function() I # Only reads the value of I
  
  # Return list with options
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## Reads a "cache list", generated by makeCacheMatrix, and either calculates, 
## via solve(x), the inverse of X, or only read its value from the cache.
cacheSolve <- function(x, ...) {
  
  # Read the inverse value
  I <- x$getInverse()
  
  # Check it I was already calculated and was stored in the cach
  if(!is.null(I)) {
    
    message("Matrix Inverted! (Cache value)")
    return(I) # Returns the value o I and exists function
    
  }
  
  # If I wasn't calculated, aka "NULL", than solve X.
  # Get value of X
  X <- x$get()
  
  # Solve X and store result in I
  I <- solve(X, ...)
  
  # Cache the inverse
  x$setInverse(I)
  
  message("Matrix Inverted!")
  
  #Return I
  I
  
}